### PR TITLE
Support RTL for both Android & IOS

### PR DESCRIPTION
**Pull request by omerman**
As a followup for the issue I opened: #996 
I believe that all of the non working RTL issues are now solved.

* Tab underline supports RTL.
* ViewPagerAndroid supports RTL.
* Checked it for both IOS and Android.

### CODE REVIEW

**Comment by omerman** [comment]
Not ready yet, still has some issues

**Comment by omerman** [comment]
The PR is ready now. Checked it for both IOS and Android.

**Comment by aliazizi** [comment]
I try this and get this error

> TypeError: this.props.scrollValue.addListener is not a function

**Comment by omerman** [comment]
I believe that I fixed the error :)

I understand you are using `ScrollableTabBar` or `FacebookTabBar`..
I only fully tested the `DefaultTabBar` component,
so feel free to check `ScrollableTabBar` & `FacebookTabBar` and maybe improve this PR.

**Comment by aliazizi** [comment]
Ok I try that
still in `DefaultTabBar` there is has problem whit click animation. the animation play in left side when I click right tab

**Comment by momoliyao** [comment]
> DefaultTabBar

the same

**Comment by omerman** [comment]
@aliazizi 
I believe that the tab click should be working now :)

**Comment by rzrobert** [comment]
832dc9c0-c9c7-11e6-9ce7-0449d9447b58

```
"react": "16.4.1",
"react-native": "0.55.2",
```
I have the same problem in Android。Are you fix this problem too? @omerman

**Comment by rzrobert** [comment]
someone replace ViewPagerAndroid to ScrollView, I don`t think that is a good solution

**Comment by zivchen** [comment]
Any news about this conflict?
@omerman  do you have a repository that i can use for RTL support?

**Comment by omerman** [comment]
@zivchen I'm sorry I stopped looking into it... I have a specific use case in a private project of mine and my patch works good. You are welcome to continue the work I've already made

**Comment by saeedaallshore** [comment]
Hi @omerman! Can you show the fix? I am facing the same issue. Transition between tabs is very slow with  renderTabBar={() => <ScrollableTabBar />}.

**Comment by omerman** [comment]
@saeedaallshore I stopped using it a long time ago.
I'm using react navigation, it has a tab navigation component and it works perfectly for ltr & rtl.

**Comment by novinhubcom** [comment]
@saeedaallshore use this library it's work pretty fine
https://github.com/satya164/react-native-tab-view

**Comment by omerman** [comment]
Closing it. Again, if someone needs RTL support, you should use react navigations scrollable tab view.

**Pull request closed without merging**
