### PR TITLE
Removed unnecessary .getNode() method call on referenced scrollView

### PR DESCRIPTION
**Pull request by ejdigby**
See #1085

### CODE REVIEW

**Comment by ejdigby** [comment]
See depreciation notes here: https://reactnative.dev/blog/2020/03/26/version-0.62#deprecations

**Comment by ejdigby** [comment]
@ptomasroos Any chance this could get looked at & merged soon? Causes a warning every time I swipe between views

**Comment by ptomasroos** [comment]
Thanks. My fault. Missed this.

**Comment by zmnv** [comment]
#1101

**Comment by KristineTrona** [comment]
Can we have a new release including this fix?

**Comment by saeedahmed2023** [comment]
remove .getNode from nodeModule->react-native-scrollable-tab-view->index.j
Screenshot 2022-01-08 at 3 59 55 PM
s

**Comment by shoaibarif244** [comment]
@saeedahmed2023 Love U yr Thanks

**Comment by shoaibarif244** [comment]
جزاک اللہ خیرا کثیرا❤❤❤

**Pull request merged**
